apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-api
  namespace: demo-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-api
  template:
    metadata:
      labels:
        app: demo-service-api
    spec:
      containers:
        - name: demo-service-api
          image: registry.example.com/demo-service-api:latest
          ports:
            - containerPort: 8000
