apiVersion: v1
kind: Service
metadata:
  name: demo-service-api
  namespace: demo-services
spec:
  selector:
    app: demo-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
